### ISSUE TITLE
Bug - Force Close

### ISSUE THREAD

**Issue by TurKurT656** [chenupt/SpringIndicator#4]
Hi, I've imported your lib and used with default viewPager(Adapter extends FragmentPagerAdapter). but this error happend at runtime:

03-08 20:55:07.671  30808-30808/ir.uniquedev.timeout I/Adreno200-EGL﹕ <qeglDrvAPI_eglInitialize:299>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_JB_REL_RB1.04.01.01.06.043_msm8660_surf_JB_REL_RB1.2_CL2428086_release_AU (CL2428086)
    Build Date: 11/15/12 Thu
    Local Branch:
    Remote Branch: m/jb_rel_rb1.2
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_JB_REL_RB1.04.01.01.06.043 + e534df6 + 951c251 + 07bf631 + 6aa3ec7 + e04e486 + 9f5646a + 855d11b +  NOTHING
03-08 20:55:07.741  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x5a889000 size:2088960 offset:0 fd:63
03-08 20:55:07.741  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x4d80b000 size:4096 offset:0 fd:65
03-08 20:55:07.811  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x5aa87000 size:2088960 offset:0 fd:68
03-08 20:55:07.821  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x556c1000 size:4096 offset:0 fd:70
03-08 20:55:08.121  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x5ad85000 size:2088960 offset:0 fd:72
03-08 20:55:08.121  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x5619a000 size:4096 offset:0 fd:74
03-08 20:55:08.141  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x5af83000 size:2088960 offset:0 fd:76
03-08 20:55:08.141  30808-30808/ir.uniquedev.timeout D/memalloc﹕ ion: Mapped buffer base:0x56479000 size:4096 offset:0 fd:78
03-08 20:55:11.274  30808-30808/ir.uniquedev.timeout W/ResourceType﹕ Skipping entry 0x7f08001c in package table 0 because it is not complex!
03-08 20:55:11.284  30808-30808/ir.uniquedev.timeout W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40d05680)
03-08 20:55:11.294  30808-30808/ir.uniquedev.timeout E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.uniquedev.timeout/ir.uniquedev.timeout.FeaturesActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class github.chenupt.springindicator.SpringIndicator
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.access$600(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class github.chenupt.springindicator.SpringIndicator
            at android.view.LayoutInflater.createView(LayoutInflater.java)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at ir.uniquedev.timeout.FeaturesActivity.onCreate(FeaturesActivity.java:20)
            at android.app.Activity.performCreate(Activity.java)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.access$600(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java)
            at android.view.LayoutInflater.createView(LayoutInflater.java)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at ir.uniquedev.timeout.FeaturesActivity.onCreate(FeaturesActivity.java:20)
            at android.app.Activity.performCreate(Activity.java)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.access$600(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: Int array resource ID #0x7f08001c
            at android.content.res.Resources.getIntArray(Resources.java)
            at github.chenupt.springindicator.SpringIndicator.initAttrs(SpringIndicator.java:98)
            at github.chenupt.springindicator.SpringIndicator.<init>(SpringIndicator.java:75)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java)
            at android.view.LayoutInflater.createView(LayoutInflater.java)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at ir.uniquedev.timeout.FeaturesActivity.onCreate(FeaturesActivity.java:20)
            at android.app.Activity.performCreate(Activity.java)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
            at android.app.ActivityThread.access$600(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by chenupt** [comment]
It seems that getIntArray is error when loading attrs. 
The sample code which like this:
```java
    app:siIndicatorColors="@array/indicator_colors"

    <array name="indicator_colors">
        <item>@color/indicator_1</item>
        <item>@color/indicator_2</item>
        <item>@color/indicator_3</item>
        <item>@color/indicator_4</item>
    </array>
···
Can you push your code if you still have the issue?
